# Generated by Django 5.2.4 on 2025-08-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companion',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
