# Generated by Django 5.2.4 on 2025-08-06 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_rename_owner_companion_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='age',
        ),
        migrations.AddField(
            model_name='companion',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 12, 41, 46, 382389, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
